### ISSUE TITLE
Bug: Calling `$lsx` with no argument will be outputted nothing

### ISSUE THREAD

**Issue by skomma** [weseek/crowi-plugin-lsx#1]
# What happens?
- Calling `$lsx` with no argument will be outputted nothing.
```
$lsx()
```

# What is the expected result?
- output the links of child pages

**Comment by yuki-takei** [comment]
umm.. It doesn't represent on my environment.
Could you get server logs?

try this:

```bash
DEBUG=crowi-plugin:lsx:util:LsxPageListRenderer npm start
```

**Comment by yuki-takei** [comment]
I got it!
Didn't you write `$lsx()` on the page that have some Japanese page name, did it?


How to represent?
-------------------

1. create a page that includes CJK strings in the path
  ex: `/資料/foo`
1. goto the page created now
1. write `$lsx()`

**Comment by yuki-takei** [comment]
It turned out to be a [weseek/crowi-plus](https://github.com/weseek/crowi-plus) bug rather than this plugin's bug.

This will be handed over to weseek/crowi-plus #26

**Comment by yuki-takei** [comment]
weseek/crowi-plus #26
