### ISSUE TITLE
Imprv: リストアップ順序を、デフォルトで page path 昇順に

### ISSUE THREAD

**Issue by takuma-watanabe** [weseek/crowi-plugin-lsx#8]
`$lsx(/Sandbox)` のように利用した場合に、 `/Sandbox` 配下のページを更新すると lsx によりリストアップされるページの並び順が変わることがある。
ページ名の辞書順等、一定のルールでリストアップしてほしい。

crowi-plugin-lsx ^1.3.8 を利用しています。

**Comment by yuki-takei** [comment]
@takuma-watanabe こちらですが、再現を確認できません。`reverse` オプションなしの場合は英数昇順、`reverse=true` 指定で英数降順に並ぶため、正常に見えます。

もう少し詳しい内容を教えてください。

* crowi-plus 本体のバージョン
* 具体的にどのような名前のページを作成しているか
    * どの順番で作成したか
* `$lsx(/Sandbox)` を記述しているページのパス
* `$lsx(/Sandbox, reverse=true)` と書くとどうなるか

よろしくお願いいたします。

**Comment by takuma-watanabe** [comment]
すみません、指摘内容が正確ではありませんでした。
`/Sandbox`  直下のページではなく、下層ディレクトリを1つ挟んだ、更にその下層のページの並び順が不定になっているように見えます。

![image](https://user-images.githubusercontent.com/32568002/36359223-16887612-155c-11e8-9a19-08958b231d7e.png)

デモサイトの以下のページで再現が確認可能です。
[/lsx_plugin_test](https://demo.crowi-plus.org/5a8a214eeb5f3e0024f70a7c)

**Comment by takuma-watanabe** [comment]
@yuki-takei crowi-plus の動作環境は以下の通りです。

| item     | version |
| ---      | --- |
|OS        |CentOS Linux release 7.4.1708 (Core)|
|crowi-plus|2.3.9|
|node.js   |6.12.3|
|npm       |4.6.1|
|Using Docker|yes|
|Using [crowi-plus-docker-compose](https://github.com/weseek/crowi-plus-docker-compose)|yes|

**Comment by yuki-takei** [comment]
@takuma-watanabe 結局ローカルでは再現できなかったのですが、コードは「reverse 指定がない場合は sort order を指定しない」設定になっていたため、そこが原因だと判断し、デフォルトで sort order を指定するように書き換えて v1.3.9 として publish しました。

そちらをデモにディプロイしたところ、 [/lsx_plugin_test](https://demo.crowi-plus.org/5a8a214eeb5f3e0024f70a7c) では期待される動作を示すようになりました。

ご確認をお願いいたします。

**Comment by takuma-watanabe** [comment]
@yuki-takei ありがとうございました。
crowi-plus v2.4.2 + crowi-plugin-lsx v1.3.9 で期待動作していることが確認できました。
